/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and versions */
        get: operations["_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and versions */
        get: operations["_health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a generated artifact's bytes
         * @description Stream a stored artifact, with a length and resumable ranges.
         *
         *     `Content-Length` is always sent, which is the whole basis of a client-side
         *     progress bar. `Range` is honoured, so a transfer that fails partway resumes
         *     rather than starting over — generation was already paid for.
         *
         *     Args:
         *         request: The incoming request, read for the caller's label and Range.
         *         artifact_id: The artifact to fetch.
         *
         *     Returns:
         *         Response: 200 with the whole artifact, or 206 with the requested range.
         */
        get: operations["artifact_content_v1_artifacts__artifact_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a batch of prompts
         * @description Submit many prompts as one job and return its handle.
         *
         *     Args:
         *         request: Engine selection and the prompts to run.
         *
         *     Returns:
         *         BatchJobResponse: The job handle. Poll it with GET /v1/batches/{id}.
         *
         *     Raises:
         *         HTTPException: 400 when the batch is empty or custom_ids collide, both
         *             of which the caller can fix without a provider round trip.
         */
        post: operations["submit_batch_v1_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status of a submitted batch
         * @description Report a batch's current status and counts.
         *
         *     Args:
         *         batch_id: Handle returned by the submit call.
         *         engine: Engine that holds the batch. Required, because the id alone
         *             does not identify which provider account it lives in.
         *         model: Model the batch was submitted against, when it was not default.
         *
         *     Returns:
         *         BatchJobResponse: Refreshed status and counts.
         */
        get: operations["get_batch_v1_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel an in-progress batch
         * @description Ask the provider to cancel a batch.
         *
         *     Cancellation is a request, not a guarantee: items already processed stay
         *     processed and stay billed, which is why the response carries the counts.
         *
         *     Args:
         *         batch_id: Handle returned by the submit call.
         *         engine: Engine that holds the batch.
         *         model: Model the batch was submitted against, when it was not default.
         *
         *     Returns:
         *         BatchJobResponse: The job in its canceling or canceled state.
         */
        post: operations["cancel_batch_v1_batches__batch_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/batches/{batch_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results of an ended batch
         * @description Return every result for a batch that has ended.
         *
         *     Correlate results to requests by `custom_id`; providers return them in
         *     their own order.
         *
         *     Args:
         *         batch_id: Handle returned by the submit call.
         *         engine: Engine that holds the batch.
         *         model: Model the batch was submitted against, when it was not default.
         *
         *     Returns:
         *         BatchResultsResponse: One entry per request, in provider order.
         */
        get: operations["get_batch_results_v1_batches__batch_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text completion (buffered or SSE stream)
         * @description Generate a completion, buffered by default or streamed over SSE.
         *
         *     Args:
         *         http_request: The incoming request, read for the caller's label so
         *             an attached artifact is looked up in that caller's own store.
         *         request: Engine selection, prompt, attachments, and generation options.
         *
         *     Returns:
         *         CompletionResponse | StreamingResponse: The completion text, or an SSE
         *             stream when `stream` is true.
         */
        post: operations["completions_v1_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One stateless conversation turn, with optional tool schemas
         * @description Run one assistant turn; the caller owns history and tool execution.
         *
         *     Args:
         *         request: System prompt, full history, optional tools, and the previous
         *             turn's opaque token.
         *
         *     Returns:
         *         ConversationTurnResponse: The assistant turn, any tool calls the caller
         *             must execute, and the token to echo back next turn.
         */
        post: operations["conversation_turn_v1_conversations_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Embedding vectors for one or more inputs
         * @description Embed one or more inputs.
         *
         *     Args:
         *         request: Engine selection and the texts to embed.
         *
         *     Returns:
         *         EmbeddingsResponse: One vector per input, index-paired to the inputs.
         */
        post: operations["embeddings_v1_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate images and store them for streaming
         * @description Generate images, store each one, and return references to fetch them.
         *
         *     The bytes are not inlined. Base64 in a JSON body would inflate them by a
         *     third and cap the response at what a single buffer can hold, and it would
         *     give a caller no way to show progress or resume a failed transfer.
         *
         *     Args:
         *         request: The incoming request, read for the caller's label.
         *         body: Prompt and image properties.
         *
         *     Returns:
         *         ImageResponse: One reference per generated image.
         */
        post: operations["images_v1_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogued models with capabilities, pricing, and lifecycle
         * @description List an engine's models with their lifecycle and pricing.
         *
         *     `engine` is required rather than optional. Listing every engine would mean
         *     constructing a client for each one on a single request, and client
         *     construction re-reads configuration and makes a network round trip on
         *     Gemini. One engine per call keeps the cost of this endpoint predictable.
         *
         *     Args:
         *         engine: Engine token to list.
         *
         *     Returns:
         *         ModelsResponse: Provider-reported models, plus registry entries for
         *             lifecycle and pricing.
         */
        get: operations["models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize speech and store it for streaming
         * @description Turn text into audio, store it, and return a reference to fetch it.
         *
         *     Args:
         *         http_request: The incoming request, read for the caller's label so the
         *             clip is stored under the caller who asked for it.
         *         request: Text, voice, format, and delivery options.
         *
         *     Returns:
         *         SpeechResponse: A reference to the stored clip.
         */
        post: operations["speech_v1_speech_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schema-validated structured output
         * @description Generate output validated against a caller-supplied JSON schema.
         *
         *     Args:
         *         request: Engine selection, prompt or messages, and the response schema.
         *
         *     Returns:
         *         StructuredResponse: Parsed data with the finish reason and usage. Data
         *             is null on any finish reason other than `complete`.
         */
        post: operations["structured_v1_structured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provider-side token count for a prompt
         * @description Count tokens in a prompt, as the provider counts them.
         *
         *     `count_tokens` is synchronous and some providers make a network call for
         *     it, so it runs in the threadpool rather than blocking the event loop.
         *
         *     Args:
         *         request: Engine selection and the prompt to measure.
         *
         *     Returns:
         *         TokenCountResponse: The provider-side token count.
         */
        post: operations["token_count_v1_tokens_count_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a video generation and return its job handle
         * @description Begin generating a video and return immediately with a job handle.
         *
         *     Poll `/v1/videos/{job_id}` for status, or subscribe to
         *     `/v1/videos/{job_id}/events` for progress as it changes.
         *
         *     Args:
         *         request: The incoming request, read for the caller's label.
         *         body: Prompt and video properties.
         *
         *     Returns:
         *         JobResponse: The job, queued.
         */
        post: operations["create_video_v1_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Video job status and progress
         * @description Report a video job's progress and, once ready, its artifacts.
         *
         *     Args:
         *         request: The incoming request, read for the caller's label.
         *         job_id: Handle returned when the job was created.
         *
         *     Returns:
         *         JobResponse: Current status, percent, and any artifacts.
         */
        get: operations["video_job_v1_videos__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Progress events for a video job (SSE)
         * @description Stream a job's progress as it changes, until it finishes.
         *
         *     Progress during generation cannot be measured by the client, because no
         *     bytes exist yet. It is published here instead, and each event says whether
         *     the figure was reported by the provider or estimated from elapsed time.
         *
         *     Once the job is ready the caller fetches the artifact, and progress for
         *     *that* phase needs nothing from the service beyond `Content-Length`.
         *
         *     Args:
         *         request: The incoming request, read for the caller's label.
         *         job_id: Handle returned when the job was created.
         *
         *     Returns:
         *         StreamingResponse: `text/event-stream` of progress events.
         */
        get: operations["video_job_events_v1_videos__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Voices, output formats, and what this engine supports
         * @description List the voices and formats available, with the engine's capabilities.
         *
         *     Args:
         *         locale: Restrict to one locale, e.g. `en-US`. Worth using: an engine
         *             may publish thousands of voices, and the response returns a page
         *             while reporting the true total.
         *
         *     Returns:
         *         VoiceCatalogResponse: Voices, formats, capabilities, and defaults.
         */
        get: operations["voices_v1_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactRef
         * @description Where to fetch one generated artifact, and how big it is.
         *
         *     The bytes are not inlined. They are fetched from `/v1/artifacts/{id}/content`,
         *     which sends `Content-Length` so a client can draw a real progress bar, and
         *     honours `Range` so a failed transfer resumes instead of restarting.
         */
        ArtifactRef: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Kind
             * @description One of: image, video.
             */
            kind: string;
            /** Mime Type */
            mime_type: string;
            /**
             * Size Bytes
             * @description Exact byte count, matching the Content-Length of a full fetch.
             */
            size_bytes: number;
            /**
             * Url Path
             * @description Path to fetch the bytes from, relative to the service root.
             */
            url_path: string;
        };
        /**
         * Attachment
         * @description One non-text input attached to a prompt.
         *
         *     The bytes come from one of two places and exactly one must be given.
         *     `data` carries them base64-encoded, which is what a JSON body allows.
         *     `artifact_id` names something already in the artifact store, so an image
         *     this service generated can be asked about without being downloaded and
         *     uploaded again.
         *
         *     Which attachment types a model accepts is the library's decision, not this
         *     service's: it validates the MIME type against what the provider path
         *     supports and refuses the rest. Today that is images. A request carrying
         *     anything else comes back as a 400 quoting the library's own reason, and
         *     widening upstream widens this endpoint without a change here.
         */
        Attachment: {
            /**
             * Artifact Id
             * @description An artifact previously returned by /v1/images or /v1/videos, read from the store instead of being re-uploaded. Only the caller who created it can attach it.
             */
            artifact_id?: string | null;
            /**
             * Data
             * @description Base64-encoded bytes. Mutually exclusive with artifact_id.
             */
            data?: string | null;
            /**
             * Mime Type
             * @description Content type of the attached bytes, required with `data`. Taken from the stored artifact when `artifact_id` is used instead.
             */
            mime_type?: string | null;
        };
        /**
         * AudioFormatInfo
         * @description One output format this engine can produce.
         */
        AudioFormatInfo: {
            /** Description */
            description?: string | null;
            /** File Extension */
            file_extension?: string | null;
            /**
             * Key
             * @description Pass this back as `audio_format`.
             */
            key: string;
            /** Sample Rate Hz */
            sample_rate_hz?: number | null;
        };
        /**
         * BatchJobResponse
         * @description A batch's identity and current state.
         *
         *     `batch_id` has to be presented with the same `engine` and `model` on every
         *     later call. A batch lives inside one provider's account, and the client
         *     that can ask about it is the one built for that engine, so the id alone
         *     does not identify it.
         *
         *     Counts are optional because providers report different subsets, and the
         *     library passes through what it was given rather than inventing zeros that
         *     would read as measured values.
         */
        BatchJobResponse: {
            /** Batch Id */
            batch_id: string;
            /** Canceled Count */
            canceled_count?: number | null;
            /**
             * Ended At Utc
             * @description ISO 8601 UTC timestamp, or null.
             */
            ended_at_utc?: string | null;
            /** Engine */
            engine: string;
            /** Errored Count */
            errored_count?: number | null;
            /** Expired Count */
            expired_count?: number | null;
            /** Model */
            model?: string | null;
            /** Processing Count */
            processing_count?: number | null;
            /** Provider Batch Id */
            provider_batch_id?: string | null;
            /** Request Count */
            request_count?: number | null;
            /**
             * Status
             * @description One of: in_progress, canceling, ended, failed, expired, canceled. Results are available once the status is ended.
             */
            status: string;
            /**
             * Submitted At Utc
             * @description ISO 8601 UTC timestamp, or null.
             */
            submitted_at_utc?: string | null;
            /** Succeeded Count */
            succeeded_count?: number | null;
        };
        /**
         * BatchRequestItem
         * @description One prompt in a batch, carrying the caller's own identifier.
         *
         *     `custom_id` is how a result is matched back to its request. Providers
         *     return results in their own order, so position cannot be relied on.
         */
        BatchRequestItem: {
            /**
             * Custom Id
             * @description Caller's identifier for this item; must be unique in the batch.
             */
            custom_id: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /** Prompt */
            prompt: string;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * BatchResultItem
         * @description One request's outcome.
         *
         *     An item can fail while the batch as a whole ends normally, so `status` is
         *     per item and `text` is null unless it succeeded.
         */
        BatchResultItem: {
            /** Custom Id */
            custom_id: string;
            /** Error Message */
            error_message?: string | null;
            /**
             * Status
             * @description One of: succeeded, errored, canceled, expired.
             */
            status: string;
            /** Text */
            text?: string | null;
            usage: components["schemas"]["TokenUsage"];
        };
        /**
         * BatchResultsResponse
         * @description Every result for an ended batch.
         *
         *     Correlate by `custom_id`. Provider order is not request order.
         */
        BatchResultsResponse: {
            /** Batch Id */
            batch_id: string;
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /** Results */
            results: components["schemas"]["BatchResultItem"][];
        };
        /**
         * BatchSubmitRequest
         * @description A batch of prompts submitted as one job.
         *
         *     Batch pricing is roughly half of interactive at the providers that offer
         *     it, in exchange for latency measured in hours rather than seconds.
         */
        BatchSubmitRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /**
             * Requests
             * @description Prompts to run; each needs a custom_id unique within the batch.
             */
            requests: components["schemas"]["BatchRequestItem"][];
        };
        /** CompletionRequest */
        CompletionRequest: {
            /**
             * Attachments
             * @description Non-text inputs to send with the prompt. Works on the streaming path as well as the buffered one. Base64 inflates by a third, so an attachment sent as `data` counts against HTTP_MAX_REQUEST_BYTES (1 MiB by default) and will be refused with 413 well before the library's own 20 MB cap; an `artifact_id` carries no body weight at all.
             */
            attachments?: components["schemas"]["Attachment"][] | null;
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt: string;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /**
             * Stream
             * @description When true the response is text/event-stream (SSE). Streaming responses bypass PII redaction middleware by library design.
             * @default false
             */
            stream: boolean;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * CompletionResponse
         * @description Buffered completion result.
         *
         *     Text only, because `asend_prompt` returns a bare `str`. Token usage and a
         *     finish reason would require routing this through the conversation call
         *     instead, which is a different provider path than the endpoint documents.
         *     `/v1/conversations/turn` and `/v1/structured` return both natively.
         */
        CompletionResponse: {
            /**
             * Engine
             * @description Engine that served the request.
             */
            engine: string;
            /**
             * Model
             * @description Model requested, or null for the engine default.
             */
            model?: string | null;
            /**
             * Text
             * @description Generated completion text.
             */
            text: string;
        };
        /** ConversationTurnRequest */
        ConversationTurnRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /**
             * Messages
             * @description Full conversation history; the service holds no state between turns. Replay a previous assistant turn by placing its conversation_token as the content of an assistant message, in the position it occurred: {"role": "assistant", "content": "<conversation_token>"}. Ordering is yours, because only you know where a new user message belongs relative to it.
             */
            messages: {
                [key: string]: unknown;
            }[];
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /** System Prompt */
            system_prompt: string;
            /** Tool Choice */
            tool_choice?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolSchema"][] | null;
        };
        /**
         * ConversationTurnResponse
         * @description One assistant turn.
         *
         *     `conversation_token` is opaque. Store it and echo it back on the next turn
         *     without inspecting it: it carries provider-specific content whose shape
         *     changes with the engine and the library version, and parsing it would turn
         *     a provider's internal representation into this service's contract.
         */
        ConversationTurnResponse: {
            /**
             * Conversation Token
             * @description Opaque. Echo back verbatim as previous_turn_token on the next turn. Never parse it; the encoding is an implementation detail that changes between service versions.
             */
            conversation_token?: string | null;
            /** Engine */
            engine: string;
            /**
             * Finish Reason
             * @description One of: complete, length, tool_use, refusal.
             */
            finish_reason: string;
            /** Model */
            model?: string | null;
            /** Text */
            text?: string | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            usage: components["schemas"]["TokenUsage"];
            /**
             * Usd Cost
             * @description Cost of this call in USD, priced from the usage above, or null when the model carries no token rates in the registry. A string for the same reason the rates are strings: these are decimal money values, and binary floating point cannot hold them exactly. Null is not zero — null means the price is unknown, and a call that genuinely cost nothing reports a numeric zero.
             */
            usd_cost?: string | null;
        };
        /**
         * EmbeddingVector
         * @description One input's embedding, paired with the index of the input it came from.
         *
         *     The index is explicit rather than positional-by-convention so a caller can
         *     reorder or filter without losing the mapping back to their inputs.
         */
        EmbeddingVector: {
            /** Embedding */
            embedding: number[];
            /** Index */
            index: number;
        };
        /** EmbeddingsRequest */
        EmbeddingsRequest: {
            /**
             * Engine
             * @description Embeddings engine token, e.g. 'openai', 'google-gemini', 'voyage'.
             */
            engine: string;
            /**
             * Input Type
             * @description What the text is for, typically 'query' or 'document'. Voyage and Gemini embed a search query differently from a stored document, so a retrieval index built without this and searched with it returns worse matches. Forwarded to the provider unchanged; engines that do not use it ignore it.
             */
            input_type?: string | null;
            /**
             * Inputs
             * @description Texts to embed; one vector per input.
             */
            inputs: string[];
            /** Model */
            model?: string | null;
        };
        /** EmbeddingsResponse */
        EmbeddingsResponse: {
            /**
             * Dimensions
             * @description Length of each vector, when any were returned.
             */
            dimensions?: number | null;
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /** Vectors */
            vectors: components["schemas"]["EmbeddingVector"][];
        };
        /**
         * ErrorResponse
         * @description Uniform failure body for every error the service maps from the library.
         *
         *     `provider_status` is the provider's own HTTP status when one was reported.
         *     It is present for diagnosis and never equals the status of this response:
         *     a provider 500 surfaces as a 502 here, and a provider 401 as a 502 too,
         *     since callers hold no provider credentials.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable cause.
             */
            detail: string;
            /**
             * Engine
             * @description Engine token that failed, when known.
             */
            engine?: string | null;
            /**
             * Error
             * @description Machine-readable error code.
             */
            error: string;
            /**
             * Provider Status
             * @description HTTP status reported by the provider, when one was reported.
             */
            provider_status?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Library Version */
            library_version: string;
            /** Service Version */
            service_version: string;
            /** Status */
            status: string;
        };
        /**
         * ImageRequest
         * @description A prompt and the shape of the images wanted from it.
         */
        ImageRequest: {
            /**
             * Background
             * @description Provider background hint.
             * @default auto
             */
            background: string;
            /** Height */
            height?: number | null;
            /**
             * Image Format
             * @description One of: png, jpeg, webp.
             * @default png
             */
            image_format: string;
            /**
             * Model
             * @description Image model, or null for the configured default.
             */
            model?: string | null;
            /**
             * Num Images
             * @description How many images to generate. Capped because each one is fetched and stored before the response returns.
             * @default 1
             */
            num_images: number;
            /** Prompt */
            prompt: string;
            /**
             * Quality
             * @description Provider quality hint.
             * @default medium
             */
            quality: string;
            /** Width */
            width?: number | null;
        };
        /**
         * ImageResponse
         * @description What a generation produced, without the bytes.
         */
        ImageResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactRef"][];
            /** Engine */
            engine?: string | null;
            /** Model */
            model?: string | null;
        };
        /**
         * JobResponse
         * @description A generation job's progress.
         *
         *     `percent` is a number a UI can render directly. `estimated` says whether it
         *     was measured or derived: providers do not all report progress, so an
         *     estimate from elapsed time is offered rather than nothing, and is labelled
         *     so a caller can present it honestly. An estimate never reaches 100 — only
         *     the job finishing sets that.
         */
        JobResponse: {
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactRef"][];
            /** Engine */
            engine?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Estimated
             * @description True when percent is derived from elapsed time, not reported.
             */
            estimated: boolean;
            /** Job Id */
            job_id: string;
            /** Model */
            model?: string | null;
            /**
             * Percent
             * @description Completion in [0, 100].
             */
            percent: number;
            /**
             * Status
             * @description One of: queued, generating, ready, failed.
             */
            status: string;
        };
        /**
         * ModelInfo
         * @description Catalog entry for one model.
         *
         *     `status` and `sunset_date` are the fields worth reading before pinning a
         *     model: the library refuses retired models outright, and a deprecated one
         *     names its replacement.
         */
        ModelInfo: {
            /** Model */
            model: string;
            pricing?: components["schemas"]["ModelPricing"] | null;
            /** Provider */
            provider: string;
            /** Recommended Replacement */
            recommended_replacement?: string | null;
            /**
             * Status
             * @description One of: active, deprecated, retired.
             */
            status: string;
            /** Sunset Date */
            sunset_date?: string | null;
        };
        /** ModelPricing */
        ModelPricing: {
            /** Confidence */
            confidence: string;
            /** Currency */
            currency: string;
            /** Effective Date */
            effective_date: string;
            /** Notes */
            notes?: string | null;
            /** Source */
            source: string;
            token_rates?: components["schemas"]["TokenRates"] | null;
            /** Unit */
            unit: string;
        };
        /**
         * ModelsResponse
         * @description Model catalog for one engine.
         *
         *     `models` lists what the provider reports as available right now.
         *     `catalog` carries the library's registry entries — lifecycle and pricing —
         *     which cover models the provider may not list and omit models the registry
         *     has not catalogued. The two are reported separately rather than merged,
         *     because a model missing from one is a different fact than a model missing
         *     from the other.
         */
        ModelsResponse: {
            /** Catalog */
            catalog: components["schemas"]["ModelInfo"][];
            /** Engine */
            engine: string;
            /** Models */
            models: string[];
        };
        /**
         * SpeechRequest
         * @description Text to synthesize, and how it should sound.
         *
         *     The result is stored rather than inlined, exactly as a generated image is,
         *     so it comes back as a reference and is fetched with a progress bar and a
         *     resumable range.
         */
        SpeechRequest: {
            /**
             * Audio Format
             * @description An `audio_formats.key` from /v1/voices; omit for the default.
             */
            audio_format?: string | null;
            /**
             * Emotion Prompt
             * @description Direction for delivery, e.g. 'sound cheerful'. Refused when the engine reports no emotion control.
             */
            emotion_prompt?: string | null;
            /**
             * Speaking Rate
             * @default 1
             */
            speaking_rate: number;
            /** Text */
            text: string;
            /**
             * Use Ssml
             * @description Treat the text as SSML. Refused when the engine reports no SSML support.
             * @default false
             */
            use_ssml: boolean;
            /**
             * Voice Id
             * @description From /v1/voices; omit for the engine's default.
             */
            voice_id?: string | null;
        };
        /**
         * SpeechResponse
         * @description A synthesized clip, addressed rather than inlined.
         */
        SpeechResponse: {
            artifact: components["schemas"]["ArtifactRef"];
            /** Audio Format */
            audio_format?: string | null;
            /**
             * Duration Seconds
             * @description Length of the clip, when the engine can measure it.
             */
            duration_seconds?: number | null;
            /** Engine */
            engine: string;
            /** Voice Id */
            voice_id?: string | null;
        };
        /** StructuredRequest */
        StructuredRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /** Messages */
            messages?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /**
             * Response Schema
             * @description JSON schema the completion must validate against.
             */
            response_schema: {
                [key: string]: unknown;
            };
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * StructuredResponse
         * @description Schema-validated structured output.
         *
         *     `data` is null whenever `finish_reason` is not `complete`: the model was
         *     cut off by the token budget or refused. Read `finish_reason` before `data`,
         *     or a truncated response is indistinguishable from an empty result.
         */
        StructuredResponse: {
            /**
             * Data
             * @description Parsed object, or null when finish_reason is not 'complete'.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Engine */
            engine: string;
            /**
             * Finish Reason
             * @description One of: complete, length, tool_use, refusal.
             */
            finish_reason: string;
            /** Model */
            model?: string | null;
            /**
             * Raw Text
             * @description Model output before parsing, for diagnosing a null data field.
             */
            raw_text: string;
            usage: components["schemas"]["TokenUsage"];
            /**
             * Usd Cost
             * @description Cost of this call in USD, priced from the usage above, or null when the model carries no token rates in the registry. A string for the same reason the rates are strings: these are decimal money values, and binary floating point cannot hold them exactly. Null is not zero — null means the price is unknown, and a call that genuinely cost nothing reports a numeric zero.
             */
            usd_cost?: string | null;
        };
        /** TokenCountRequest */
        TokenCountRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt: string;
        };
        /** TokenCountResponse */
        TokenCountResponse: {
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /**
             * Token Count
             * @description Provider-side count for the prompt.
             */
            token_count: number;
        };
        /**
         * TokenRates
         * @description Per-million-token prices.
         *
         *     Serialized as strings, not floats. These are decimal money values, and
         *     binary floating point cannot represent them exactly — a rate of 0.075
         *     becoming 0.07499999999999999 in JSON would be wrong in a field callers may
         *     use to compute or display cost.
         */
        TokenRates: {
            /** Cached Input Per 1M */
            cached_input_per_1m?: string | null;
            /** Input Per 1M */
            input_per_1m: string;
            /** Output Per 1M */
            output_per_1m?: string | null;
        };
        /**
         * TokenUsage
         * @description Token counts for one call, as the provider reported them.
         *
         *     Every field is optional because not every provider reports every count,
         *     and the library passes through what it was given rather than inventing
         *     zeros that would read as measured values.
         */
        TokenUsage: {
            /** Cached Input Tokens */
            cached_input_tokens?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /**
         * ToolCall
         * @description A tool the model wants invoked.
         *
         *     The service never executes these. The caller runs the tool and sends the
         *     result back on the next turn, which is what keeps the service stateless
         *     and keeps tool execution inside the caller's own trust boundary.
         */
        ToolCall: {
            /**
             * Id
             * @description Echo this back when returning the tool result.
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
        };
        /**
         * ToolSchema
         * @description Mirror of ai_api_unified.AITool — a schema, never executable code.
         */
        ToolSchema: {
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Strict
             * @default false
             */
            strict: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VideoRequest
         * @description A prompt and the shape of the video wanted from it.
         */
        VideoRequest: {
            /** Aspect Ratio */
            aspect_ratio?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Engine
             * @description Video engine, or null for the configured default.
             */
            engine?: string | null;
            /** Fps */
            fps?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Output Format
             * @default mp4
             */
            output_format: string;
            /** Prompt */
            prompt: string;
            /** Resolution */
            resolution?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /**
         * VoiceCapabilities
         * @description What the configured voice engine can and cannot do.
         *
         *     Engines differ enough that a caller cannot assume. OpenAI streams and has
         *     no emotion control; Google has emotion control and speech to text and does
         *     not stream. Reading this before building a request avoids finding out by
         *     being refused.
         */
        VoiceCapabilities: {
            /** Max Speaking Rate */
            max_speaking_rate?: number | null;
            /** Min Speaking Rate */
            min_speaking_rate?: number | null;
            /** Supports Emotion Control */
            supports_emotion_control?: boolean | null;
            /** Supports Speech To Text */
            supports_speech_to_text?: boolean | null;
            /** Supports Ssml */
            supports_ssml?: boolean | null;
            /** Supports Streaming */
            supports_streaming?: boolean | null;
            /** Supports Word Timestamps */
            supports_word_timestamps?: boolean | null;
        };
        /**
         * VoiceCatalogResponse
         * @description Everything needed to build a speech request for this deployment.
         */
        VoiceCatalogResponse: {
            /** Audio Formats */
            audio_formats: components["schemas"]["AudioFormatInfo"][];
            capabilities: components["schemas"]["VoiceCapabilities"];
            /** Default Audio Format */
            default_audio_format?: string | null;
            /** Default Voice Id */
            default_voice_id?: string | null;
            /** Engine */
            engine: string;
            /**
             * Total Voices
             * @description How many voices the engine has, which may exceed the number returned. Narrow with the `locale` query parameter.
             */
            total_voices: number;
            /** Voices */
            voices: components["schemas"]["VoiceInfo"][];
        };
        /**
         * VoiceInfo
         * @description One voice a caller can ask for by id.
         */
        VoiceInfo: {
            /** Accent */
            accent?: string | null;
            /** Gender */
            gender?: string | null;
            /** Language */
            language?: string | null;
            /** Locale */
            locale?: string | null;
            /** Voice Id */
            voice_id: string;
            /** Voice Name */
            voice_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    _health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    artifact_content_v1_artifacts__artifact_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_v1_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_batch_v1_batches__batch_id__get: {
        parameters: {
            query: {
                engine: string;
                model?: string | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_batch_v1_batches__batch_id__cancel_post: {
        parameters: {
            query: {
                engine: string;
                model?: string | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_batch_results_v1_batches__batch_id__results_get: {
        parameters: {
            query: {
                engine: string;
                model?: string | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResultsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    completions_v1_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionRequest"];
            };
        };
        responses: {
            /** @description Buffered completion. With stream=true the response is instead text/event-stream carrying chunk events, then one terminal done or error event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    conversation_turn_v1_conversations_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    embeddings_v1_embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    images_v1_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    models_v1_models_get: {
        parameters: {
            query: {
                engine: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    speech_v1_speech_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeechRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeechResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    structured_v1_structured_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    token_count_v1_tokens_count_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCountResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_video_v1_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    video_job_v1_videos__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_job_events_v1_videos__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voices_v1_voices_get: {
        parameters: {
            query?: {
                locale?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceCatalogResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
