/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and versions */
        get: operations["_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and versions */
        get: operations["_health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text completion (buffered or SSE stream)
         * @description Generate a completion, buffered by default or streamed over SSE.
         *
         *     Args:
         *         request: Engine selection, prompt, and generation options.
         *
         *     Returns:
         *         CompletionResponse | StreamingResponse: The completion text, or an SSE
         *             stream when `stream` is true.
         */
        post: operations["completions_v1_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One stateless conversation turn, with optional tool schemas
         * @description Run one assistant turn; the caller owns history and tool execution.
         *
         *     Args:
         *         request: System prompt, full history, optional tools, and the previous
         *             turn's opaque token.
         *
         *     Returns:
         *         ConversationTurnResponse: The assistant turn, any tool calls the caller
         *             must execute, and the token to echo back next turn.
         */
        post: operations["conversation_turn_v1_conversations_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Embedding vectors for one or more inputs
         * @description Embed one or more inputs.
         *
         *     Args:
         *         request: Engine selection and the texts to embed.
         *
         *     Returns:
         *         EmbeddingsResponse: One vector per input, index-paired to the inputs.
         */
        post: operations["embeddings_v1_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogued models with capabilities, pricing, and lifecycle
         * @description List an engine's models with their lifecycle and pricing.
         *
         *     `engine` is required rather than optional. Listing every engine would mean
         *     constructing a client for each one on a single request, and client
         *     construction re-reads configuration and makes a network round trip on
         *     Gemini. One engine per call keeps the cost of this endpoint predictable.
         *
         *     Args:
         *         engine: Engine token to list.
         *
         *     Returns:
         *         ModelsResponse: Provider-reported models, plus registry entries for
         *             lifecycle and pricing.
         */
        get: operations["models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/structured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Schema-validated structured output
         * @description Generate output validated against a caller-supplied JSON schema.
         *
         *     Args:
         *         request: Engine selection, prompt or messages, and the response schema.
         *
         *     Returns:
         *         StructuredResponse: Parsed data with the finish reason and usage. Data
         *             is null on any finish reason other than `complete`.
         */
        post: operations["structured_v1_structured_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provider-side token count for a prompt
         * @description Count tokens in a prompt, as the provider counts them.
         *
         *     `count_tokens` is synchronous and some providers make a network call for
         *     it, so it runs in the threadpool rather than blocking the event loop.
         *
         *     Args:
         *         request: Engine selection and the prompt to measure.
         *
         *     Returns:
         *         TokenCountResponse: The provider-side token count.
         */
        post: operations["token_count_v1_tokens_count_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompletionRequest */
        CompletionRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt: string;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /**
             * Stream
             * @description When true the response is text/event-stream (SSE). Streaming responses bypass PII redaction middleware by library design.
             * @default false
             */
            stream: boolean;
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * CompletionResponse
         * @description Buffered completion result.
         *
         *     Text only, because `asend_prompt` returns a bare `str`. Token usage and a
         *     finish reason would require routing this through the conversation call
         *     instead, which is a different provider path than the endpoint documents.
         *     `/v1/conversations/turn` and `/v1/structured` return both natively.
         */
        CompletionResponse: {
            /**
             * Engine
             * @description Engine that served the request.
             */
            engine: string;
            /**
             * Model
             * @description Model requested, or null for the engine default.
             */
            model?: string | null;
            /**
             * Text
             * @description Generated completion text.
             */
            text: string;
        };
        /** ConversationTurnRequest */
        ConversationTurnRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /**
             * Messages
             * @description Full conversation history; the service holds no state between turns. Replay a previous assistant turn by placing its conversation_token as the content of an assistant message, in the position it occurred: {"role": "assistant", "content": "<conversation_token>"}. Ordering is yours, because only you know where a new user message belongs relative to it.
             */
            messages: {
                [key: string]: unknown;
            }[];
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /** System Prompt */
            system_prompt: string;
            /** Tool Choice */
            tool_choice?: string | null;
            /** Tools */
            tools?: components["schemas"]["ToolSchema"][] | null;
        };
        /**
         * ConversationTurnResponse
         * @description One assistant turn.
         *
         *     `conversation_token` is opaque. Store it and echo it back on the next turn
         *     without inspecting it: it carries provider-specific content whose shape
         *     changes with the engine and the library version, and parsing it would turn
         *     a provider's internal representation into this service's contract.
         */
        ConversationTurnResponse: {
            /**
             * Conversation Token
             * @description Opaque. Echo back verbatim as previous_turn_token on the next turn. Never parse it; the encoding is an implementation detail that changes between service versions.
             */
            conversation_token?: string | null;
            /** Engine */
            engine: string;
            /**
             * Finish Reason
             * @description One of: complete, length, tool_use, refusal.
             */
            finish_reason: string;
            /** Model */
            model?: string | null;
            /** Text */
            text?: string | null;
            /** Tool Calls */
            tool_calls?: components["schemas"]["ToolCall"][];
            usage: components["schemas"]["TokenUsage"];
            /**
             * Usd Cost
             * @description Cost of this call in USD, priced from the usage above, or null when the model carries no token rates in the registry. A string for the same reason the rates are strings: these are decimal money values, and binary floating point cannot hold them exactly. Null is not zero — null means the price is unknown, and a call that genuinely cost nothing reports a numeric zero.
             */
            usd_cost?: string | null;
        };
        /**
         * EmbeddingVector
         * @description One input's embedding, paired with the index of the input it came from.
         *
         *     The index is explicit rather than positional-by-convention so a caller can
         *     reorder or filter without losing the mapping back to their inputs.
         */
        EmbeddingVector: {
            /** Embedding */
            embedding: number[];
            /** Index */
            index: number;
        };
        /** EmbeddingsRequest */
        EmbeddingsRequest: {
            /**
             * Engine
             * @description Embeddings engine token, e.g. 'openai', 'google-gemini', 'voyage'.
             */
            engine: string;
            /**
             * Input Type
             * @description What the text is for, typically 'query' or 'document'. Voyage and Gemini embed a search query differently from a stored document, so a retrieval index built without this and searched with it returns worse matches. Forwarded to the provider unchanged; engines that do not use it ignore it.
             */
            input_type?: string | null;
            /**
             * Inputs
             * @description Texts to embed; one vector per input.
             */
            inputs: string[];
            /** Model */
            model?: string | null;
        };
        /** EmbeddingsResponse */
        EmbeddingsResponse: {
            /**
             * Dimensions
             * @description Length of each vector, when any were returned.
             */
            dimensions?: number | null;
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /** Vectors */
            vectors: components["schemas"]["EmbeddingVector"][];
        };
        /**
         * ErrorResponse
         * @description Uniform failure body for every error the service maps from the library.
         *
         *     `provider_status` is the provider's own HTTP status when one was reported.
         *     It is present for diagnosis and never equals the status of this response:
         *     a provider 500 surfaces as a 502 here, and a provider 401 as a 502 too,
         *     since callers hold no provider credentials.
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable cause.
             */
            detail: string;
            /**
             * Engine
             * @description Engine token that failed, when known.
             */
            engine?: string | null;
            /**
             * Error
             * @description Machine-readable error code.
             */
            error: string;
            /**
             * Provider Status
             * @description HTTP status reported by the provider, when one was reported.
             */
            provider_status?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Api Version */
            api_version: string;
            /** Library Version */
            library_version: string;
            /** Service Version */
            service_version: string;
            /** Status */
            status: string;
        };
        /**
         * ModelInfo
         * @description Catalog entry for one model.
         *
         *     `status` and `sunset_date` are the fields worth reading before pinning a
         *     model: the library refuses retired models outright, and a deprecated one
         *     names its replacement.
         */
        ModelInfo: {
            /** Model */
            model: string;
            pricing?: components["schemas"]["ModelPricing"] | null;
            /** Provider */
            provider: string;
            /** Recommended Replacement */
            recommended_replacement?: string | null;
            /**
             * Status
             * @description One of: active, deprecated, retired.
             */
            status: string;
            /** Sunset Date */
            sunset_date?: string | null;
        };
        /** ModelPricing */
        ModelPricing: {
            /** Confidence */
            confidence: string;
            /** Currency */
            currency: string;
            /** Effective Date */
            effective_date: string;
            /** Notes */
            notes?: string | null;
            /** Source */
            source: string;
            token_rates?: components["schemas"]["TokenRates"] | null;
            /** Unit */
            unit: string;
        };
        /**
         * ModelsResponse
         * @description Model catalog for one engine.
         *
         *     `models` lists what the provider reports as available right now.
         *     `catalog` carries the library's registry entries — lifecycle and pricing —
         *     which cover models the provider may not list and omit models the registry
         *     has not catalogued. The two are reported separately rather than merged,
         *     because a model missing from one is a different fact than a model missing
         *     from the other.
         */
        ModelsResponse: {
            /** Catalog */
            catalog: components["schemas"]["ModelInfo"][];
            /** Engine */
            engine: string;
            /** Models */
            models: string[];
        };
        /** StructuredRequest */
        StructuredRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /** Max Response Tokens */
            max_response_tokens?: number | null;
            /** Messages */
            messages?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Request Timeout Seconds */
            request_timeout_seconds?: number | null;
            /**
             * Response Schema
             * @description JSON schema the completion must validate against.
             */
            response_schema: {
                [key: string]: unknown;
            };
            /** System Prompt */
            system_prompt?: string | null;
        };
        /**
         * StructuredResponse
         * @description Schema-validated structured output.
         *
         *     `data` is null whenever `finish_reason` is not `complete`: the model was
         *     cut off by the token budget or refused. Read `finish_reason` before `data`,
         *     or a truncated response is indistinguishable from an empty result.
         */
        StructuredResponse: {
            /**
             * Data
             * @description Parsed object, or null when finish_reason is not 'complete'.
             */
            data?: {
                [key: string]: unknown;
            } | null;
            /** Engine */
            engine: string;
            /**
             * Finish Reason
             * @description One of: complete, length, tool_use, refusal.
             */
            finish_reason: string;
            /** Model */
            model?: string | null;
            /**
             * Raw Text
             * @description Model output before parsing, for diagnosing a null data field.
             */
            raw_text: string;
            usage: components["schemas"]["TokenUsage"];
            /**
             * Usd Cost
             * @description Cost of this call in USD, priced from the usage above, or null when the model carries no token rates in the registry. A string for the same reason the rates are strings: these are decimal money values, and binary floating point cannot hold them exactly. Null is not zero — null means the price is unknown, and a call that genuinely cost nothing reports a numeric zero.
             */
            usd_cost?: string | null;
        };
        /** TokenCountRequest */
        TokenCountRequest: {
            /**
             * Engine
             * @description Completions engine token, e.g. 'openai', 'claude', 'google-gemini'.
             */
            engine: string;
            /**
             * Model
             * @description Model name; omit to use the engine's default model.
             */
            model?: string | null;
            /** Prompt */
            prompt: string;
        };
        /** TokenCountResponse */
        TokenCountResponse: {
            /** Engine */
            engine: string;
            /** Model */
            model?: string | null;
            /**
             * Token Count
             * @description Provider-side count for the prompt.
             */
            token_count: number;
        };
        /**
         * TokenRates
         * @description Per-million-token prices.
         *
         *     Serialized as strings, not floats. These are decimal money values, and
         *     binary floating point cannot represent them exactly — a rate of 0.075
         *     becoming 0.07499999999999999 in JSON would be wrong in a field callers may
         *     use to compute or display cost.
         */
        TokenRates: {
            /** Cached Input Per 1M */
            cached_input_per_1m?: string | null;
            /** Input Per 1M */
            input_per_1m: string;
            /** Output Per 1M */
            output_per_1m?: string | null;
        };
        /**
         * TokenUsage
         * @description Token counts for one call, as the provider reported them.
         *
         *     Every field is optional because not every provider reports every count,
         *     and the library passes through what it was given rather than inventing
         *     zeros that would read as measured values.
         */
        TokenUsage: {
            /** Cached Input Tokens */
            cached_input_tokens?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /**
         * ToolCall
         * @description A tool the model wants invoked.
         *
         *     The service never executes these. The caller runs the tool and sends the
         *     result back on the next turn, which is what keeps the service stateless
         *     and keeps tool execution inside the caller's own trust boundary.
         */
        ToolCall: {
            /**
             * Id
             * @description Echo this back when returning the tool result.
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
        };
        /**
         * ToolSchema
         * @description Mirror of ai_api_unified.AITool — a schema, never executable code.
         */
        ToolSchema: {
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /**
             * Strict
             * @default false
             */
            strict: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    _health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    completions_v1_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionRequest"];
            };
        };
        responses: {
            /** @description Buffered completion. With stream=true the response is instead text/event-stream carrying chunk events, then one terminal done or error event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    conversation_turn_v1_conversations_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    embeddings_v1_embeddings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    models_v1_models_get: {
        parameters: {
            query: {
                engine: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    structured_v1_structured_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructuredRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructuredResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    token_count_v1_tokens_count_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenCountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCountResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
